services:
  user_authentication:
    container_name: user_authentication.iot
    build:
      context: ./services/user_authentication
    env_file:
      - ./services/user_authentication/.env
    volumes:
      - "./.iot/db:/app/db"

  fridge:
    container_name: fridge.iot
    build:
      context: ./services/fridge
    env_file:
      - ./services/fridge/.env
    command: yarn start

  nginx:
    build:
      context: ./services/routing
    ports:
      - "80:8000"
    volumes:
      - ./services/routing/nginx.conf:/etc/nginx/conf.d/default.conf
