services:
  user_authentication:
    develop:
      watch:
        - action: sync+restart
          path: ./services/user_authentication/user_authentication
          target: /app
  fridge:
    build:
      target: dev
    environment:
      - PORT=8000
    command: yarn dev
    develop:
      watch:
        - action: sync
          path: ./services/fridge/src
          target: /app/src
